version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: taringuita-db
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: taringuita
      POSTGRES_PASSWORD: taringuita123
      POSTGRES_DB: taringuita
    volumes:
      - taringuita-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taringuita -d taringuita']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  taringuita-postgres-data:
    driver: local
